# Generated by Django 5.0.7 on 2024-07-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='00:00:00')),
                ('end_time', models.TimeField(default='00:00:00')),
            ],
        ),
        migrations.AddConstraint(
            model_name='time_slots',
            constraint=models.UniqueConstraint(fields=('start_time', 'end_time'), name='unique_time_slot'),
        ),
    ]
