# Generated by Django 5.0.7 on 2024-08-01 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_time_slots_time_slots_unique_time_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate_per',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_training_cost',
            fields=[
                ('cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.time_slots')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user_profile')),
            ],
        ),
    ]
