# Generated by Django 5.0.7 on 2024-08-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rate_per_personal_training_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('phone_number2', models.CharField(max_length=50)),
            ],
        ),
    ]
