# Generated by Django 5.0.7 on 2024-08-10 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_address_platform_user_trainer_delete_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('range', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Bodytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_provided', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Platform_user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('BMI', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.bodytype')),
                ('blood_pressure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.bloodpressure')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.goals')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(upload_to='certificate_pdfs/')),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=5)),
                ('verification', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='personal_training_cost',
            name='timing',
        ),
        migrations.RemoveField(
            model_name='personal_training_cost',
            name='user',
        ),
        migrations.DeleteModel(
            name='Rate_per',
        ),
        migrations.AddField(
            model_name='platform_user',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainer',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platform_user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_image/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_image/'),
        ),
        migrations.AddField(
            model_name='platform_user_data',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.platform_user'),
        ),
        migrations.RenameModel(
            old_name='Time_slots',
            new_name='Slots',
        ),
        migrations.AddField(
            model_name='trainer_data',
            name='time_Slots_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_data_time_slots_1', to='account.slots'),
        ),
        migrations.AddField(
            model_name='trainer_data',
            name='time_Slots_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_data_time_slots_2', to='account.slots'),
        ),
        migrations.AddField(
            model_name='trainer_data',
            name='time_Slots_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_data_time_slots_3', to='account.slots'),
        ),
        migrations.AddField(
            model_name='trainer_data',
            name='time_Slots_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_data_time_slots_4', to='account.slots'),
        ),
        migrations.AddField(
            model_name='trainer_data',
            name='time_Slots_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_data_time_slots_5', to='account.slots'),
        ),
        migrations.AddField(
            model_name='trainer_data',
            name='time_Slots_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_data_time_slots_6', to='account.slots'),
        ),
        migrations.AddField(
            model_name='trainer_data',
            name='time_Slots_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_data_time_slots_7', to='account.slots'),
        ),
        migrations.AddField(
            model_name='trainer_data',
            name='trainer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.trainer'),
        ),
        migrations.DeleteModel(
            name='Personal_training_cost',
        ),
    ]
