# Generated by Django 5.0.7 on 2024-08-12 17:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_bloodpressure_bodytype_goals_platform_user_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trainer_data',
            new_name='TrainerData',
        ),
        migrations.RemoveField(
            model_name='platform_user_data',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='platform_user_data',
            name='Body_type',
        ),
        migrations.RemoveField(
            model_name='platform_user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='platform_user_data',
            name='user',
        ),
        migrations.RemoveField(
            model_name='platform_user_data',
            name='goal',
        ),
        migrations.AddField(
            model_name='trainer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(null=True, upload_to='profile_image/')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=10)),
                ('created_at', models.DateTimeField()),
                ('subscription', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Body_type', models.CharField(blank=True, choices=[('Ectomorph', 'Ectomorph'), ('Endomorph', 'Endomorph'), ('Mesomorph', 'Mesomorph'), ('Pear or triangle', 'Pear or triangle'), ('Inverted triangle', 'Inverted triangle'), ('Rectangle', 'Rectangle'), ('Hourglass', 'Hourglass'), ('Oval or apple', 'Oval or apple')], max_length=50)),
                ('blood_pressure', models.CharField(blank=True, choices=[('Normal', 'LESS THAN 120\tand\tLESS THAN 80'), ('Elevated', '120 - 129\tand\tLESS THAN 80'), ('HIGH BLOOD PRESSURE (HYPERTENSION) STAGE 1', '130 - 139\tor\t80 - 89'), ('HIGH BLOOD PRESSURE (HYPERTENSION) STAGE 2', '140 OR HIGHER\tor\t90 OR HIGHER'), ('HYPERTENSIVE CRISIS (consult your doctor immediately)', 'HIGHER THAN 180\tand/or\tHIGHER THAN 120')], max_length=100)),
                ('BMI', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.goals')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.platformuser')),
            ],
        ),
        migrations.DeleteModel(
            name='BloodPressure',
        ),
        migrations.DeleteModel(
            name='Bodytype',
        ),
        migrations.DeleteModel(
            name='Platform_user',
        ),
        migrations.DeleteModel(
            name='Platform_user_data',
        ),
    ]
