# Generated by Django 5.0.7 on 2024-08-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_trainer_data_trainerdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
