# Generated by Django 5.0.7 on 2024-08-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_platformuser_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerdata',
            name='certificate',
        ),
        migrations.AddField(
            model_name='trainer',
            name='certificate',
            field=models.FileField(null=True, upload_to='certificate_pdfs/'),
        ),
    ]
