# Generated by Django 5.0.7 on 2024-08-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_trainerdata_certificate_trainer_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='certificate',
            field=models.FileField(default='', upload_to='certificate_pdfs/'),
            preserve_default=False,
        ),
    ]
