# Generated by Django 5.0.7 on 2024-08-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_trainer_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slots',
            options={'verbose_name': 'Slot'},
        ),
    ]
