# Generated by Django 5.0.7 on 2024-08-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_slots_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
