# Generated by Django 5.0.7 on 2024-08-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_platformuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformuser',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
