# Generated by Django 5.0.7 on 2024-08-20 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_platformuser_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformuserdata',
            old_name='user',
            new_name='platform_user',
        ),
    ]
