# Generated by Django 5.0.7 on 2024-08-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_user_platformuserdata_platform_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformuser',
            options={'permissions': [('is_platform_user', 'Is platform user')]},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'permissions': [('is_trainer', 'Is trainer')]},
        ),
    ]
