# Generated by Django 5.0.7 on 2024-09-04 16:11

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0015_alter_platformuser_options_alter_trainer_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlanTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.CharField(choices=[('M', 'Monthly (1 month)'), ('Q ', 'Quarterly (3 months) '), ('S', 'Half-Yearly (6 months)'), ('Y', 'Yearly (12 months)')], max_length=50)),
                ('features', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='HireTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('M', 'Monthly (1 month)'), ('Q ', 'Quarterly (3 months) '), ('S', 'Half-Yearly (6 months)'), ('Y', 'Yearly (12 months)')], max_length=50)),
                ('hiring_date', models.DateTimeField(auto_now_add=True)),
                ('termination_date', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('hiring_status', models.BooleanField(default=False)),
                ('hired_trainer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.trainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.platformuser')),
            ],
        ),
        migrations.CreateModel(
            name='SubscribedTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
                ('termination_date', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('subscription_status', models.BooleanField(default=False)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.trainer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.subscriptionplantrainer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(default='0', max_length=128)),
                ('payment_signature', models.CharField(default='0', max_length=128)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed')], default='pending', max_length=20)),
                ('method', models.CharField(choices=[('card', 'card'), ('COD', 'COD'), ('UPI', 'UPI'), ('net_banking', 'net_banking')], max_length=20)),
                ('hired_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.hiretrainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('subscribed_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.subscribedtrainer')),
            ],
        ),
    ]
