# Generated by Django 5.0.7 on 2024-09-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecord',
            name='hired_trainer',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='subscribed_trainer',
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='is_platform_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='is_trainer',
            field=models.BooleanField(default=False),
        ),
    ]
