# Generated by Django 5.0.7 on 2024-09-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_hiretrainer_hiring_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretrainer',
            name='hiring_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
