# Generated by Django 5.0.7 on 2024-09-05 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_remove_paymentrecord_hired_trainer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecord',
            name='is_platform_user',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='is_trainer',
        ),
    ]
