# Generated by Django 5.0.7 on 2024-09-07 03:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_hiretrainer_hiring_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribedtrainer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
