# Generated by Django 5.0.7 on 2024-09-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_hiretrainer_hiring_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='method',
            field=models.CharField(choices=[('card', 'card'), ('COD', 'COD'), ('UPI', 'UPI'), ('Razor Pay', 'Razor Pay')], max_length=20),
        ),
    ]
