# Generated by Django 5.0.7 on 2024-09-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_platformuser_options_alter_trainer_options'),
        ('subscription', '0006_alter_paymentrecord_method'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribedtrainer',
            name='unique_date_subscription_trainer',
        ),
        migrations.AddConstraint(
            model_name='subscribedtrainer',
            constraint=models.UniqueConstraint(fields=('trainer', 'plan', 'subscription_status', 'subscription_date'), name='unique_date_subscription_trainer'),
        ),
    ]
