# Generated by Django 5.0.7 on 2024-09-06 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0015_alter_platformuser_options_alter_trainer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_pdf', models.FileField(upload_to='plans/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.trainer')),
                ('uploaded_for_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.platformuser')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_data/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='VideoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.platformuser')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.video')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customplans',
            constraint=models.UniqueConstraint(fields=('trainer', 'uploaded_for_user', 'from_date', 'to_date'), name='unique_date_trainer'),
        ),
        migrations.AddConstraint(
            model_name='customplans',
            constraint=models.UniqueConstraint(fields=('uploaded_for_user', 'week'), name='unique_data_user'),
        ),
    ]
