# Generated by Django 5.0.7 on 2024-08-31 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_platformuser_options_alter_trainer_options'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customplans',
            name='unique_date_trainer',
        ),
        migrations.RemoveConstraint(
            model_name='customplans',
            name='unique_data_user',
        ),
        migrations.AlterUniqueTogether(
            name='customplans',
            unique_together={('trainer', 'from_date', 'to_date'), ('uploaded_for_user', 'week')},
        ),
    ]
