# Generated by Django 5.0.3 on 2024-08-26 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_user_platformuserdata_platform_user'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customplans',
            name='uploaded_for',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.platformuser'),
        ),
        migrations.AlterField(
            model_name='customplans',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.trainer'),
        ),
    ]
