# Generated by Django 5.0.7 on 2024-09-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_platformuser_options_alter_trainer_options'),
        ('data', '0002_remove_customplans_unique_date_trainer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customplans',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='customplans',
            constraint=models.UniqueConstraint(fields=('trainer', 'from_date', 'to_date'), name='unique_date_trainer'),
        ),
        migrations.AddConstraint(
            model_name='customplans',
            constraint=models.UniqueConstraint(fields=('uploaded_for_user', 'week'), name='unique_data_user'),
        ),
    ]
