# Generated by Django 5.0.7 on 2024-09-11 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_platformuser_options_alter_trainer_options'),
        ('data', '0002_image_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.platformuser')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.video')),
            ],
        ),
    ]
