# Generated by Django 5.0.7 on 2024-09-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_platformuser_options_alter_trainer_options'),
        ('data', '0003_alter_customplans_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customplans',
            name='unique_date_trainer',
        ),
        migrations.AddConstraint(
            model_name='customplans',
            constraint=models.UniqueConstraint(fields=('trainer', 'uploaded_for_user', 'from_date', 'to_date'), name='unique_date_trainer'),
        ),
    ]
