# Generated by Django 5.0.7 on 2024-09-11 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_saveddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddata',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.image'),
        ),
        migrations.AlterField(
            model_name='saveddata',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.video'),
        ),
    ]
